### ISSUE TITLE
Jupyter notebooks for a better start

### ISSUE THREAD

**Issue by unfassbarstephan** [je-suis-tm/quant-trading#10]
Hi,

your github repo is really great and very clear, so i want to deal more with your tools. However, it takes a little bit of time to get used to it.

But for the beginning I would like to see some exemplary Jupyter notebooks with your explanations from the readme. In this way you were able to get directly into the topic.

Maybe you could create some notebooks, I would really like it!

**Comment by je-suis-tm** [comment]
Hi unfassbarstephan, thanks for your appreciation. If you have check out my other repos, e.g. graph theory, you will see I have used Jupyter notebook a lot. But I don't use Jupyter in quant trading. Simply becuz I expect people to embed scripts of this repo into their own trading system. It makes more sense to take the software development approach. However, I will try to use more Jupyter inside the projects if it helps people to understand what I am actually doing.
