### ISSUE TITLE
Possible forward bias in pair trading code

### ISSUE THREAD

**Issue by maitreyaverma** [je-suis-tm/quant-trading#12]
`   positions1=capital0//max(df1['asset1'])
`
`    positions2=capital0//max(df1['asset2'])
`
Hey, I think there is a possible forward bias in the pair trading code. When you size the positions in accordance to the maximum value an asset takes over the entire duration (including the time which has not been seen by the strategy), then the knowledge of maximum value over the duration peeps in.
A different approach can be to size based on the prices available at time 0.

**Comment by je-suis-tm** [comment]
Hi maitreyaverma, thanks for checking the code for me. 
It's my fault that I haven't written a clear comment on this part. 

This is not a forward bias but an intentionally setting.
The idea of using `//max` is to find the most appropriate shares of each position. 
As the price goes up and down, I am taking the maximum price from god's view to ensure I can maintain the preset shares per position. 
For instance, assume the capital0 is 1000€, asset1 price is 10€ per share and positions1 is 100 shares at the moment. 
When the price reaches 20€ per share, we will not be able to purchase 100 shares cuz we are short of cash, lol

If you want to embed the script into your live trading framework, you probably should move these two arguments into the function definition.
I have updated the pair trading code and add more comments.
Again, thank you for checking with me.

T.M.
