### ISSUE TITLE
Suggestions for FX Market/Pair with Awesome Oscillator

### ISSUE THREAD

**Issue by bschmook** [je-suis-tm/quant-trading#4]
Do you have any suggestions how I could take the MACD and pair it with the Awesome Oscillator to create a live trading script on Currency, not just backtesting?

**Comment by je-suis-tm** [comment]
**Please read through the script or ReadMe.** Both MACD and Awesome are moving average based oscillators. There is no point of mixing them together. As I mentioned at the beginning of ReadMe, every trade in this repository is considered frictionless. If you want to do day trading with APIs, please learn more about the market microstructure.
