### ISSUE TITLE
New Day Data

### ISSUE THREAD

**Issue by EkremSel** [je-suis-tm/quant-trading#40]
Hi.First, thank you for the code. I am a beginner quant coder. I ve implemented another version of your code  written by Sabir Jana. 
https://github.com/sabirjana/blog/blob/master/Pair_Trading/sj_pairs_trading.ipynb

Now what I do is add the new daily close price and shift +1 in the notebook and re do the calculations . When I do this, the signals differ from the previous ones. So the problem is, if I do get a signal on that specific day, when I do the calculation again on the next day closing price, the signal from the previous day might not be there.

**Comment by je-suis-tm** [comment]
Thanks for using my code. However, if you are using a modified version of my code, you should contact Sabir Jana for your issue.

**Comment by EkremSel** [comment]
Hey there,

Using your  model, I am getting below error:

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

Any suggestions how can I overcome it?
