### ISSUE TITLE
forced brownian dynamics for stock market crash prediction

### ISSUE THREAD

**Issue by gwonchan** [je-suis-tm/quant-trading#42]
Hey Bro,

I love your works on git and want to share my ideas how to predict next market crash.
When you add external term on the brownian dynamic equation like mxdotdot +  cxdot + kx = f(x) and solve it, you will get similar pattern. you can do curve fitting and getting c,k and also m and getting market dynamic contents and use this eq to predict next crash.

Check my paper fig.3.2.

https://drive.google.com/file/d/14XCTCn6in6tEab8ZJSCww6ISkawmg5Zq/view?usp=sharing

Jason

**Comment by aaron1276** [comment]
I believe the wrong paper is attached.

**Comment by je-suis-tm** [comment]
Lol bro, is that a bait to increase your H index? Seriously, give me a DOI and I will take a look.

**Comment by gwonchan** [comment]
Now I am more interested dow index lol. Let me find it and attach here soon! ![image](https://user-images.githubusercontent.com/50343951/182616653-f9860dbc-88f1-4e38-86df-4b94fbfc74c4.png)

**Comment by gwonchan** [comment]
https://github.com/gwonchan/thesis

**Comment by gwonchan** [comment]
they are matlab tho..hahahaha too oldy

**Comment by je-suis-tm** [comment]
Jason, I didn't study mechanical engineering so your paper is a bit difficult for me to comprehend. However, I do see the similarity between your figure and market crash and I am eager to find out more. What you propose is something similar to hooke's law. But I do not understand the notation of your brownian motion. Could you point me to the specific equation/paragraph in the paper that you refer to?

**Comment by gwonchan** [comment]
Thank you for your interest in this boring work! please check eq 3.1, 3.2. and there is matlab code in my github! actually I ignored mx dot dot term and expand cx dot term using euler method! but you can add the double dot term and using Runge-cutta etc to solve the ODE numerically!

**Comment by gwonchan** [comment]
One more! please check mechanochemistry field and you will get an idea what's going on this research topic! Also there are nobel prize winners like Martin Kaplus @ harvard!

**Comment by je-suis-tm** [comment]
Haha, I studied statistics, not sure I can comprehend mechanochemistry, but I will try!
