### ISSUE TITLE
what is the gbpusd.csv 's data structure?

### ISSUE THREAD

**Issue by imcda** [je-suis-tm/quant-trading#46]
I have download the gbp/usd data from the histdata.com, but I can't find the column's name.

could you give a example file?

thanks, this project is awsome, learn a lot.

**Comment by dmidlo** [comment]
They have it posted on the histdata.com website.  I also have it at the following here on github: https://github.com/dmidlo/histdata.com-tools/blob/main/histdata.com_data_specs.md

**Comment by je-suis-tm** [comment]
Thanks @dmidlo It's been too long since I created this repo. I cannot remember anything. I will document this more properly.

**Comment by imcda** [comment]
> They have it posted on the histdata.com website. I also have it at the following here on github: https://github.com/dmidlo/histdata.com-tools/blob/main/histdata.com_data_specs.md

Thx, I will try later.
