### ISSUE TITLE
Psar problem

### ISSUE THREAD

**Issue by alanzoudc** [je-suis-tm/quant-trading#5]
Parabolic SAR backtest.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

**Comment by je-suis-tm** [comment]
Right, my bad. Try to use .loc[ ] instead of direct slicing on dataframe. If you are too lazy to do that (as I am), just ignore it. Small warning, no big deal.

**Comment by jhead67** [comment]
Gtfo. This is Spam.
