### ISSUE TITLE
Not able to generate bollinger band signals

### ISSUE THREAD

**Issue by sabirjana** [je-suis-tm/quant-trading#8]
hi,
Thanks for that great work!!
I am trying to generate just the buy/ sell signal (and not the pattern). I took the 5 years stock data however signals[signals['signals']!=0] is always empty irrespective of any stock I take. Appreciate any help.
Thank you!
**********************************************************************
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume, std, mid band, upper band, lower band, signals, cumsum, coordinates]
Index: []
![image](https://user-images.githubusercontent.com/52304765/72530829-3abdf980-3896-11ea-82fc-844ced086f04.png)

**Comment by je-suis-tm** [comment]
Can you be more specific? What do you mean by buy/sell signal? In this script, I've only used one function to generate signals which is bottom w pattern. If you are not using the pattern recognition, I assume you have built your own function. You need to check your own function thoroughly.

**Comment by sabirjana** [comment]
Thanks for the response. The issue is resolved now.

**Comment by pkjmesra** [comment]
> Thanks for the response. The issue is resolved now.

@sabirjana - What was the issue and how did you resolve it?
